"""initial schema

Revision ID: b0331e8365c3
Revises: 
Create Date: 2026-08-07 09:32:31.830318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0331e8365c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openalex_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id')
    )
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openalex_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.SmallInteger(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id')
    )
    op.create_index('ix_paper_publication_year', 'paper', ['publication_year'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openalex_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('paper_author',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'author_id')
    )
    op.create_index('ix_paper_author_author_id', 'paper_author', ['author_id'], unique=False)
    op.create_table('paper_similarity',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('similar_paper_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'similar_paper_id')
    )
    op.create_index('ix_paper_similarity_paper_id_score', 'paper_similarity', ['paper_id', 'similarity_score'], unique=False)
    op.create_table('paper_topic',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'topic_id')
    )
    op.create_index('ix_paper_topic_topic_id', 'paper_topic', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_topic_topic_id', table_name='paper_topic')
    op.drop_table('paper_topic')
    op.drop_index('ix_paper_similarity_paper_id_score', table_name='paper_similarity')
    op.drop_table('paper_similarity')
    op.drop_index('ix_paper_author_author_id', table_name='paper_author')
    op.drop_table('paper_author')
    op.drop_table('topic')
    op.drop_index('ix_paper_publication_year', table_name='paper')
    op.drop_table('paper')
    op.drop_table('author')
    # ### end Alembic commands ###